Models/Carrera.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_tarea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrera
    {
        public int IdCarrera { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Materias { get; set; }
        public Nullable<int> Ciclos { get; set; }
        public byte[] Imagen { get; set; }
    }
}

Controllers/CarrerasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using MVC_tarea.Models;
using static System.Net.WebRequestMethods;

namespace MVC_tarea.Controllers
{
    public class CarrerasController : Controller
    {
        private DonBoscoEntities db = new DonBoscoEntities();

        // GET: Carreras
        public ActionResult Index()
        {
            return View(db.Carrera.ToList());
        }

        public ActionResult Carreras()
        {
            return View(db.Carrera.ToList());
        }

        // GET: Carreras/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Carrera carrera = db.Carrera.Find(id);
            if (carrera == null)
            {
                return HttpNotFound();
            }
            return View(carrera);
        }

        // GET: Carreras/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Carreras/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdCarrera,Nombre,Descripcion,Materias,Ciclos")] Carrera carrera)
        {
            HttpPostedFileBase http = Request.Files[0];
            WebImage webImage = new WebImage(http.InputStream);
            carrera.Imagen = webImage.GetBytes();

            if (ModelState.IsValid)
            {
                db.Carrera.Add(carrera);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(carrera);
        }

        // GET: Carreras/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Carrera carrera = db.Carrera.Find(id);
            if (carrera == null)
            {
                return HttpNotFound();
            }
            return View(carrera);
        }

        // POST: Carreras/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdCarrera,Nombre,Descripcion,Materias,Ciclos,")] Carrera carrera)
        {
            byte[] ImagenActual = null;

            HttpPostedFileBase http = Request.Files[0];
            if (http == null)
            {
                ImagenActual = db.Carrera.SingleOrDefault(t => t.IdCarrera == carrera.IdCarrera).Imagen;
                carrera.Imagen = ImagenActual;
            }
            else
            {
                WebImage webImage = new WebImage(http.InputStream);
                carrera.Imagen = webImage.GetBytes();
            }

            if (ModelState.IsValid)
            {
                db.Entry(carrera).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(carrera);
        }

        // GET: Carreras/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Carrera carrera = db.Carrera.Find(id);
            if (carrera == null)
            {
                return HttpNotFound();
            }
            return View(carrera);
        }

        // POST: Carreras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Carrera carrera = db.Carrera.Find(id);
            db.Carrera.Remove(carrera);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult getImage(int id)
        {
            Carrera carrerask = db.Carrera.Find(id);
            byte[] byteimagen = carrerask.Imagen;

            MemoryStream memoryStream = new MemoryStream(byteimagen);
            Image image = Image.FromStream(memoryStream);

            memoryStream = new MemoryStream();
            image.Save(memoryStream, ImageFormat.Jpeg);
            memoryStream.Position = 0;

            return File(memoryStream, "image/jpg");

        }
    }
}

Views/Carreras/Carreras.cshtml
@model IEnumerable<MVC_tarea.Models.Carrera>

<div class="row centered bg-light p-3">
    <img src="~/Content/img/bancarrera.jpg" width="100%" alt="">
</div>

<div class="row">

    @foreach (var item in Model)
    {
        <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 my-2">
            <div class="card col-md-12 centered" style="width: 18rem;">
                <img class="card-img-top" src="@Url.Action("getImage", "Carreras", new { id = item.IdCarrera })" alt="Card image cap">
                <div class="card-body">
                    <h4 class="card-title">Carrera: </h4>@Html.DisplayFor(modelItem => item.Nombre)
                    <p class="card-text smalltext"><h4>Descripcion:</h4> @Html.DisplayFor(modelItem => item.Descripcion) </p>
                    <p class="card-text smalltext"><h4>Materias:</h4> @Html.DisplayFor(modelItem => item.Materias) </p>
                    <p class="card-text smalltext"><h4>Ciclos:</h4> @Html.DisplayFor(modelItem => item.Ciclos) </p>
                </div>
            </div>
        </div>
        
    }

</div> 

Views/Carreras/Create.cshtml
@model MVC_tarea.Models.Carrera

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Carreras", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Carrera</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Materias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Materias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Materias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ciclos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ciclos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ciclos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Imagen" value="Create"/>
            </div>
        </div>

        <div class="form-group centered">
            <div class="col-md-offset-2 col-md-10 centered">
                <input type="submit" value="Create" class="btn btn-primary my-3" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Carreras/Delete.cshtml
@model MVC_tarea.Models.Carrera

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Carrera</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Materias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Materias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ciclos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ciclos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagen)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Carreras/Details.cshtml
@model MVC_tarea.Models.Carrera

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Carrera</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Materias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Materias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ciclos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ciclos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagen)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdCarrera }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Carreras/Edit.cshtml
@model MVC_tarea.Models.Carrera

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Carreras", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Carrera</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdCarrera)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Materias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Materias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Materias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ciclos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ciclos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ciclos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Poster" />
            </div>
        </div>

        <div class="form-group centered">
            <div class="col-md-offset-2 col-md-10 centered">
                <input type="submit" value="Save" class="btn btn-primary my-3" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Carreras/Index.cshtml
@model IEnumerable<MVC_tarea.Models.Carrera>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Materias)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ciclos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Imagen)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Materias)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ciclos)
        </td>
        <td>
            <img width="100" src="@Url.Action("getImage", "Carreras", new { id = item.IdCarrera })">
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IdCarrera }) |
            @Html.ActionLink("Details", "Details", new { id=item.IdCarrera }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IdCarrera })
        </td>
    </tr>
}
</table>